export const projectsInfos = [
  {
    title: "Norda",
    subTitle: "MERN-stack CRUD project",
    description: "E-Commerce application made from scratch",
    fctList: [
      "Fully Responsive",
      "JWT secured endpoints and user authentication via Cookie",
      "Password reset functionnality",
      "DB protection with data sanitization",
      "Products pagination, filtering and sorting",
      "Admin product management (CRUD) with images preview , delete and add options",
      "RESTfull APIs",
      "Global error handling with Express",
    ],
    techs: [
      "NextJs",
      "TailwindCss",
      "MaterialUI",
      // "Node Js",
      "ExpressJs",
      // "MongoDB",
      "Mongoose",
    ],
    imgs: ["/e-shop2.png"],
    links: {
      github: "https://github.com/allaoua-rico/e-shop/tree/main",
      deployed: "https://ab-e-shop.herokuapp.com/",
    },
  },
  {
    title: "Purples",
    subTitle: "Front-End",
    description: "",
    fctList: [
      "Fully Responsive suing tailwindCss",
      "Form validation using formik and yup with error feedback",
      "Auto-refetch after CUD operations using SWR",
      "Translation using i18next",
      "Calendar: appointments displaying, custom actions on click",
      "Calendar-styling: insert css using styled-components, and create custom component (toobar,event)",
      "Time formatting and manipulation using momentJs",
      "Intuitive currency inputs",
    ],
    techs: [
      "ReactJs",
      "TailwindCss",
      "MaterialUI",
      "React Router",
      "React-big-calendar",
      "MomentJs",
      "SWR"
    ],
    imgs: ["/purples-1.png"],
    links: {
      github: "https://github.com/allaoua-rico/e-shop/tree/main",
      deployed: "https://mangomint-clone-olive.vercel.app/",
    },
  },
];
